// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYxBg-qGswb1NDXOfOqlVk5117Fm4Ir-w',
    appId: '1:826041343832:web:8e841157719c14c8088f2d',
    messagingSenderId: '826041343832',
    projectId: 'cs-messaging-app-9773d',
    authDomain: 'cs-messaging-app-9773d.firebaseapp.com',
    storageBucket: 'cs-messaging-app-9773d.appspot.com',
    measurementId: 'G-1KNTSQ036P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAWjjggYjIbPYrif923kl6zT01J4bGUHg',
    appId: '1:826041343832:android:34d51c9a078d567a088f2d',
    messagingSenderId: '826041343832',
    projectId: 'cs-messaging-app-9773d',
    storageBucket: 'cs-messaging-app-9773d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGl_jOOcYMzDEVmFF9XYsvPNkDL-O-pRs',
    appId: '1:826041343832:ios:d04567ab109e7897088f2d',
    messagingSenderId: '826041343832',
    projectId: 'cs-messaging-app-9773d',
    storageBucket: 'cs-messaging-app-9773d.appspot.com',
    iosBundleId: 'com.example.csMessagingPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGl_jOOcYMzDEVmFF9XYsvPNkDL-O-pRs',
    appId: '1:826041343832:ios:70cfcabcbf2166d9088f2d',
    messagingSenderId: '826041343832',
    projectId: 'cs-messaging-app-9773d',
    storageBucket: 'cs-messaging-app-9773d.appspot.com',
    iosBundleId: 'com.example.csMessagingPage.RunnerTests',
  );
}
